remove check in publish

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -4,10 +4,10 @@ set -e
 # TODO(ekrekr): re-enable once fork is merged to upstread.
 # ./scripts/regenerate_docs
 
-if [ "$(git status --porcelain)" ]; then 
-    echo "There are uncommitted changes; aborting." 1>&2
-    exit 1
-fi
+# if [ "$(git status --porcelain)" ]; then 
+#     echo "There are uncommitted changes; aborting." 1>&2
+#     exit 1
+# fi
 
 # Run all the tests.
 
